name: "Synology Upload Action" 
description: "Upload file to Synology Nas" 
inputs:
  host:
    required: true
    description: Synology Nas Domain
  username:
    required: true
    description: Synology account name
  password:
    required: true
    description: Synology account password
  filepath:
    required: true
    description: Local location of file 
  uploadpath:
    required: true
    description: Synology NAS location to upload file 
  filename:
    required: false
    description: Set custom file name
  overwrite: 
    required: false
    default: false
    description: If true, always overwrite exist file.
  createparent: 
    required: false
    default: false
    description: If true, make directory on Synology Nas
runs:
  using: "node12"
  main: "src/index.js"